set -g default-terminal "screen-256color"
set -ga terminal-overrides ",*256col*:Tc"
set -g mouse off #for newer versions
set -sg escape-time 0

# Use alt and arrow keys to switch between panes
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D
unbind-key Escape #Annoying problem when using vim, pressing escape will switch windows if used with other keys 
# Theming
set -g status-justify left
set -g status-style "bg=colour0"
set -ag status-style "fg=colour7"
set -g status-left ''

set -g status-right  "'#H'    #[fg=colour15]#(date +"%H:%M")  "
set -ag status-right "#[fg=colour15]#(date +"%m/%d")#[fg=colour8] #(date +"%Y") "

set -g window-status-current-format "#[fg=colour15] #F#I:#W#F "
set -g window-status-format "#[fg=colour8] #F#I:#W#F "

set -g default-terminal "screen-256color"
